"""Integrity checks for existing backup ZIP metadata."""

from __future__ import annotations

import zipfile
from pathlib import Path

from src.core.hashing import calculate_sha256
from src.core.zipper import BACKUP_INFO_FILENAME


def source_sha256_map(source_files: tuple[Path, ...]) -> dict[str, str]:
    """Return SHA256 values keyed by source file name."""

    return {path.name: calculate_sha256(path) for path in source_files}


def read_backup_sha256_map(backup_path: Path) -> dict[str, str]:
    """Read source-file SHA256 values from a backup ZIP metadata file."""

    if not zipfile.is_zipfile(backup_path):
        return {}

    try:
        with zipfile.ZipFile(backup_path) as archive:
            if BACKUP_INFO_FILENAME not in archive.namelist():
                return {}
            content = archive.read(BACKUP_INFO_FILENAME).decode("utf-8", errors="ignore")
    except (OSError, zipfile.BadZipFile):
        return {}

    return _parse_backup_info_sha256(content)


def has_sha256_conflict(source_files: tuple[Path, ...], backup_path: Path) -> bool:
    """Return whether source files differ from an existing backup with SHA metadata."""

    planned_hashes = source_sha256_map(source_files)
    existing_hashes = read_backup_sha256_map(backup_path)
    if not planned_hashes or not existing_hashes:
        return False
    return planned_hashes != existing_hashes


def _parse_backup_info_sha256(content: str) -> dict[str, str]:
    """Parse the `Included files` section generated by the application."""

    hashes: dict[str, str] = {}
    current_file: str | None = None
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if line.startswith("- "):
            current_file = line[2:].strip()
            continue
        if current_file and line.startswith("SHA256:"):
            hashes[current_file] = line.partition(":")[2].strip().upper()
            current_file = None
    return hashes
